# Generated by Django 5.1.1 on 2024-09-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cargo_num', models.IntegerField()),
                ('places_in_cargo', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'trains',
            },
        ),
    ]
